services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm run build && npm start"
    networks:
      - test_network


  db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: brain-agriculture
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - test_network

volumes:
  db_data:

networks:
  test_network:
